
GO
/****** Object:  Table [dbo].[GHE]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GHE](
	[MaGhe] [nvarchar](2) NOT NULL,
	[MaPhong] [nvarchar](2) NOT NULL,
	[TrangThai] [bit] NULL,
 CONSTRAINT [PK_GHE] PRIMARY KEY CLUSTERED 
(
	[MaGhe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKhach] [nvarchar](20) NOT NULL,
	[TenKhach] [nvarchar](50) NOT NULL,
	[SDT] [int] NULL,
	[NgayTao] [datetime] NULL,
 CONSTRAINT [PK_KHACH] PRIMARY KEY CLUSTERED 
(
	[MaKhach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIPHIM]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIPHIM](
	[MaLoaiPhim] [nvarchar](10) NOT NULL,
	[TenLoaiPhim] [nvarchar](20) NOT NULL,
	[MoTa] [text] NULL,
 CONSTRAINT [PK_LOAIPHIM] PRIMARY KEY CLUSTERED 
(
	[MaLoaiPhim] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NGUOIDUNG]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NGUOIDUNG](
	[MaNguoidung] [nvarchar](20) NOT NULL,
	[TenDangnhap] [nvarchar](50) NOT NULL,
	[Matkhau] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_NGUOIDUNG] PRIMARY KEY CLUSTERED 
(
	[MaNguoidung] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIM]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIM](
	[MaPhim] [nvarchar](30) NOT NULL,
	[TenPhim] [nvarchar](max) NOT NULL,
	[Thoiluong] [int] NOT NULL,
	[Daodien] [nvarchar](50) NULL,
	[NuocSanxuat] [nvarchar](50) NULL,
	[Hinhanh] [nvarchar](max) NULL,
	[MoTa] [text] NULL,
 CONSTRAINT [PK_PHIM] PRIMARY KEY CLUSTERED 
(
	[MaPhim] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIM_LOAIPHIM]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIM_LOAIPHIM](
	[MaPhim] [nvarchar](30) NOT NULL,
	[MaLoaiPhim] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_PHIM_LOAIPHIM_1] PRIMARY KEY CLUSTERED 
(
	[MaPhim] ASC,
	[MaLoaiPhim] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHONGCHIEUPHIM]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHONGCHIEUPHIM](
	[MaPhong] [nvarchar](2) NOT NULL,
	[TrangthaiPhongchieu] [bit] NOT NULL,
 CONSTRAINT [PK_PHONGCHIEUPHIM] PRIMARY KEY CLUSTERED 
(
	[MaPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUATCHIEU]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUATCHIEU](
	[MaSuatchieu] [nvarchar](20) NOT NULL,
	[MaPhim] [nvarchar](30) NOT NULL,
	[MaPhong] [nvarchar](2) NOT NULL,
	[MaNguoiDung] [nvarchar](20) NOT NULL,
	[Ngaychieu] [date] NULL,
	[GioBatdau] [time](0) NULL,
	[ThoiLuong] [int] NOT NULL,
	[SoVeToida] [int] NULL,
 CONSTRAINT [PK_SUATCHIEU] PRIMARY KEY CLUSTERED 
(
	[MaSuatchieu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VEXEMPHIM]    Script Date: 11/10/2024 4:20:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VEXEMPHIM](
	[MaVe] [nvarchar](20) NOT NULL,
	[MaLichChieu] [nvarchar](20) NOT NULL,
	[MaKhachHang] [nvarchar](20) NOT NULL,
	[TenGhe] [nvarchar](2) NOT NULL,
	[GiaVe] [decimal](18, 0) NULL,
	[ThoiginaDatve] [datetime] NULL,
 CONSTRAINT [PK_VEXEMPHIM] PRIMARY KEY CLUSTERED 
(
	[MaVe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GHE]  WITH CHECK ADD  CONSTRAINT [FK_GHE_PHONGCHIEUPHIM] FOREIGN KEY([MaPhong])
REFERENCES [dbo].[PHONGCHIEUPHIM] ([MaPhong])
GO
ALTER TABLE [dbo].[GHE] CHECK CONSTRAINT [FK_GHE_PHONGCHIEUPHIM]
GO
ALTER TABLE [dbo].[PHIM_LOAIPHIM]  WITH CHECK ADD  CONSTRAINT [FK_PHIM_LOAIPHIM_LOAIPHIM] FOREIGN KEY([MaLoaiPhim])
REFERENCES [dbo].[LOAIPHIM] ([MaLoaiPhim])
GO
ALTER TABLE [dbo].[PHIM_LOAIPHIM] CHECK CONSTRAINT [FK_PHIM_LOAIPHIM_LOAIPHIM]
GO
ALTER TABLE [dbo].[PHIM_LOAIPHIM]  WITH CHECK ADD  CONSTRAINT [FK_PHIM_LOAIPHIM_PHIM] FOREIGN KEY([MaPhim])
REFERENCES [dbo].[PHIM] ([MaPhim])
GO
ALTER TABLE [dbo].[PHIM_LOAIPHIM] CHECK CONSTRAINT [FK_PHIM_LOAIPHIM_PHIM]
GO
ALTER TABLE [dbo].[SUATCHIEU]  WITH CHECK ADD  CONSTRAINT [FK_SUATCHIEU_NGUOIDUNG] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NGUOIDUNG] ([MaNguoidung])
GO
ALTER TABLE [dbo].[SUATCHIEU] CHECK CONSTRAINT [FK_SUATCHIEU_NGUOIDUNG]
GO
ALTER TABLE [dbo].[SUATCHIEU]  WITH CHECK ADD  CONSTRAINT [FK_SUATCHIEU_PHIM] FOREIGN KEY([MaPhim])
REFERENCES [dbo].[PHIM] ([MaPhim])
GO
ALTER TABLE [dbo].[SUATCHIEU] CHECK CONSTRAINT [FK_SUATCHIEU_PHIM]
GO
ALTER TABLE [dbo].[SUATCHIEU]  WITH CHECK ADD  CONSTRAINT [FK_SUATCHIEU_PHONGCHIEUPHIM] FOREIGN KEY([MaPhong])
REFERENCES [dbo].[PHONGCHIEUPHIM] ([MaPhong])
GO
ALTER TABLE [dbo].[SUATCHIEU] CHECK CONSTRAINT [FK_SUATCHIEU_PHONGCHIEUPHIM]
GO
ALTER TABLE [dbo].[VEXEMPHIM]  WITH CHECK ADD  CONSTRAINT [FK_VEXEMPHIM_GHE] FOREIGN KEY([TenGhe])
REFERENCES [dbo].[GHE] ([MaGhe])
GO
ALTER TABLE [dbo].[VEXEMPHIM] CHECK CONSTRAINT [FK_VEXEMPHIM_GHE]
GO
ALTER TABLE [dbo].[VEXEMPHIM]  WITH CHECK ADD  CONSTRAINT [FK_VEXEMPHIM_KHACHHANG] FOREIGN KEY([MaKhachHang])
REFERENCES [dbo].[KHACHHANG] ([MaKhach])
GO
ALTER TABLE [dbo].[VEXEMPHIM] CHECK CONSTRAINT [FK_VEXEMPHIM_KHACHHANG]
GO
ALTER TABLE [dbo].[VEXEMPHIM]  WITH CHECK ADD  CONSTRAINT [FK_VEXEMPHIM_SUATCHIEU] FOREIGN KEY([MaLichChieu])
REFERENCES [dbo].[SUATCHIEU] ([MaSuatchieu])
GO
ALTER TABLE [dbo].[VEXEMPHIM] CHECK CONSTRAINT [FK_VEXEMPHIM_SUATCHIEU]
GO
