namespace QuanLyRapChieuPhim.MainForm
{
    partial class DashboardForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DashboardForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.buttonDatVe = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.buttonBaoCao = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonPhongChieu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonPhim = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonTaiKhoan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonSuatChieu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonTrangChu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.labelQuyen = new System.Windows.Forms.Label();
            this.labelTenDangNhap = new System.Windows.Forms.Label();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPanel1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(42)))), ((int)(((byte)(42)))));
            this.bunifuPanel1.BorderRadius = 0;
            this.bunifuPanel1.BorderThickness = 0;
            this.bunifuPanel1.Controls.Add(this.buttonDatVe);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.Padding = new System.Windows.Forms.Padding(43, 39, 43, 39);
            this.bunifuPanel1.ShowBorders = false;
            this.bunifuPanel1.Size = new System.Drawing.Size(327, 945);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // buttonDatVe
            // 
            this.buttonDatVe.AllowAnimations = true;
            this.buttonDatVe.AllowMouseEffects = true;
            this.buttonDatVe.AllowToggling = true;
            this.buttonDatVe.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonDatVe.AnimationSpeed = 150;
            this.buttonDatVe.AutoGenerateColors = false;
            this.buttonDatVe.AutoRoundBorders = false;
            this.buttonDatVe.AutoSizeLeftIcon = false;
            this.buttonDatVe.AutoSizeRightIcon = true;
            this.buttonDatVe.BackColor = System.Drawing.Color.Transparent;
            this.buttonDatVe.BackColor1 = System.Drawing.Color.White;
            this.buttonDatVe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonDatVe.BackgroundImage")));
            this.buttonDatVe.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonDatVe.ButtonText = "Giả lập đặt vé";
            this.buttonDatVe.ButtonTextMarginLeft = 0;
            this.buttonDatVe.ColorContrastOnClick = 45;
            this.buttonDatVe.ColorContrastOnHover = 45;
            this.buttonDatVe.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonDatVe.CustomizableEdges = borderEdges1;
            this.buttonDatVe.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonDatVe.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonDatVe.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonDatVe.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonDatVe.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonDatVe.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonDatVe.ForeColor = System.Drawing.Color.DimGray;
            this.buttonDatVe.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonDatVe.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonDatVe.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonDatVe.IconMarginLeft = 11;
            this.buttonDatVe.IconPadding = 10;
            this.buttonDatVe.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonDatVe.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonDatVe.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonDatVe.IconSize = 28;
            this.buttonDatVe.IdleBorderColor = System.Drawing.Color.White;
            this.buttonDatVe.IdleBorderRadius = 1;
            this.buttonDatVe.IdleBorderThickness = 1;
            this.buttonDatVe.IdleFillColor = System.Drawing.Color.White;
            this.buttonDatVe.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_OFF;
            this.buttonDatVe.IdleIconRightImage = null;
            this.buttonDatVe.IndicateFocus = true;
            this.buttonDatVe.Location = new System.Drawing.Point(29, 884);
            this.buttonDatVe.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonDatVe.Name = "buttonDatVe";
            this.buttonDatVe.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonDatVe.OnDisabledState.BorderRadius = 1;
            this.buttonDatVe.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonDatVe.OnDisabledState.BorderThickness = 1;
            this.buttonDatVe.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonDatVe.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonDatVe.OnDisabledState.IconLeftImage = null;
            this.buttonDatVe.OnDisabledState.IconRightImage = null;
            this.buttonDatVe.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonDatVe.onHoverState.BorderRadius = 1;
            this.buttonDatVe.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonDatVe.onHoverState.BorderThickness = 1;
            this.buttonDatVe.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonDatVe.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonDatVe.onHoverState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_ON;
            this.buttonDatVe.onHoverState.IconRightImage = null;
            this.buttonDatVe.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonDatVe.OnIdleState.BorderRadius = 1;
            this.buttonDatVe.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonDatVe.OnIdleState.BorderThickness = 1;
            this.buttonDatVe.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonDatVe.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonDatVe.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_OFF;
            this.buttonDatVe.OnIdleState.IconRightImage = null;
            this.buttonDatVe.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonDatVe.OnPressedState.BorderRadius = 1;
            this.buttonDatVe.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonDatVe.OnPressedState.BorderThickness = 1;
            this.buttonDatVe.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonDatVe.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonDatVe.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_ON;
            this.buttonDatVe.OnPressedState.IconRightImage = null;
            this.buttonDatVe.Size = new System.Drawing.Size(297, 47);
            this.buttonDatVe.TabIndex = 16;
            this.buttonDatVe.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonDatVe.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonDatVe.TextMarginLeft = 0;
            this.buttonDatVe.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonDatVe.UseDefaultRadiusAndThickness = true;
            this.buttonDatVe.Click += new System.EventHandler(this.buttonDatVe_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 30F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Red;
            this.bunifuLabel1.Location = new System.Drawing.Point(43, 39);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(132, 67);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "GALA";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.buttonBaoCao, 0, 5);
            this.tableLayoutPanel1.Controls.Add(this.buttonPhongChieu, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.buttonPhim, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.buttonTaiKhoan, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.buttonSuatChieu, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.buttonTrangChu, 0, 0);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 170);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.Padding = new System.Windows.Forms.Padding(21, 0, 0, 0);
            this.tableLayoutPanel1.RowCount = 6;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(327, 325);
            this.tableLayoutPanel1.TabIndex = 3;
            // 
            // buttonBaoCao
            // 
            this.buttonBaoCao.AllowAnimations = true;
            this.buttonBaoCao.AllowMouseEffects = true;
            this.buttonBaoCao.AllowToggling = true;
            this.buttonBaoCao.AnimationSpeed = 150;
            this.buttonBaoCao.AutoGenerateColors = false;
            this.buttonBaoCao.AutoRoundBorders = false;
            this.buttonBaoCao.AutoSizeLeftIcon = false;
            this.buttonBaoCao.AutoSizeRightIcon = true;
            this.buttonBaoCao.BackColor = System.Drawing.Color.Transparent;
            this.buttonBaoCao.BackColor1 = System.Drawing.Color.White;
            this.buttonBaoCao.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonBaoCao.BackgroundImage")));
            this.buttonBaoCao.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonBaoCao.ButtonText = "Báo cáo";
            this.buttonBaoCao.ButtonTextMarginLeft = 0;
            this.buttonBaoCao.ColorContrastOnClick = 45;
            this.buttonBaoCao.ColorContrastOnHover = 45;
            this.buttonBaoCao.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonBaoCao.CustomizableEdges = borderEdges2;
            this.buttonBaoCao.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonBaoCao.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonBaoCao.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonBaoCao.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonBaoCao.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonBaoCao.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonBaoCao.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonBaoCao.ForeColor = System.Drawing.Color.DimGray;
            this.buttonBaoCao.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonBaoCao.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonBaoCao.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonBaoCao.IconMarginLeft = 11;
            this.buttonBaoCao.IconPadding = 10;
            this.buttonBaoCao.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonBaoCao.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonBaoCao.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonBaoCao.IconSize = 28;
            this.buttonBaoCao.IdleBorderColor = System.Drawing.Color.White;
            this.buttonBaoCao.IdleBorderRadius = 1;
            this.buttonBaoCao.IdleBorderThickness = 1;
            this.buttonBaoCao.IdleFillColor = System.Drawing.Color.White;
            this.buttonBaoCao.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_OFF;
            this.buttonBaoCao.IdleIconRightImage = null;
            this.buttonBaoCao.IndicateFocus = true;
            this.buttonBaoCao.Location = new System.Drawing.Point(25, 274);
            this.buttonBaoCao.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonBaoCao.Name = "buttonBaoCao";
            this.buttonBaoCao.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonBaoCao.OnDisabledState.BorderRadius = 1;
            this.buttonBaoCao.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonBaoCao.OnDisabledState.BorderThickness = 1;
            this.buttonBaoCao.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonBaoCao.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonBaoCao.OnDisabledState.IconLeftImage = null;
            this.buttonBaoCao.OnDisabledState.IconRightImage = null;
            this.buttonBaoCao.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonBaoCao.onHoverState.BorderRadius = 1;
            this.buttonBaoCao.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonBaoCao.onHoverState.BorderThickness = 1;
            this.buttonBaoCao.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonBaoCao.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonBaoCao.onHoverState.IconLeftImage = null;
            this.buttonBaoCao.onHoverState.IconRightImage = null;
            this.buttonBaoCao.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonBaoCao.OnIdleState.BorderRadius = 1;
            this.buttonBaoCao.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonBaoCao.OnIdleState.BorderThickness = 1;
            this.buttonBaoCao.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonBaoCao.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonBaoCao.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_OFF;
            this.buttonBaoCao.OnIdleState.IconRightImage = null;
            this.buttonBaoCao.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonBaoCao.OnPressedState.BorderRadius = 1;
            this.buttonBaoCao.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonBaoCao.OnPressedState.BorderThickness = 1;
            this.buttonBaoCao.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonBaoCao.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonBaoCao.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_ON;
            this.buttonBaoCao.OnPressedState.IconRightImage = null;
            this.buttonBaoCao.Size = new System.Drawing.Size(298, 47);
            this.buttonBaoCao.TabIndex = 15;
            this.buttonBaoCao.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonBaoCao.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonBaoCao.TextMarginLeft = 0;
            this.buttonBaoCao.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonBaoCao.UseDefaultRadiusAndThickness = true;
            this.buttonBaoCao.Click += new System.EventHandler(this.buttonBaoCao_Click);
            // 
            // buttonPhongChieu
            // 
            this.buttonPhongChieu.AllowAnimations = true;
            this.buttonPhongChieu.AllowMouseEffects = true;
            this.buttonPhongChieu.AllowToggling = true;
            this.buttonPhongChieu.AnimationSpeed = 150;
            this.buttonPhongChieu.AutoGenerateColors = false;
            this.buttonPhongChieu.AutoRoundBorders = false;
            this.buttonPhongChieu.AutoSizeLeftIcon = false;
            this.buttonPhongChieu.AutoSizeRightIcon = true;
            this.buttonPhongChieu.BackColor = System.Drawing.Color.Transparent;
            this.buttonPhongChieu.BackColor1 = System.Drawing.Color.White;
            this.buttonPhongChieu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonPhongChieu.BackgroundImage")));
            this.buttonPhongChieu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhongChieu.ButtonText = "Quản lý phòng chiếu";
            this.buttonPhongChieu.ButtonTextMarginLeft = 0;
            this.buttonPhongChieu.ColorContrastOnClick = 45;
            this.buttonPhongChieu.ColorContrastOnHover = 45;
            this.buttonPhongChieu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.buttonPhongChieu.CustomizableEdges = borderEdges3;
            this.buttonPhongChieu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonPhongChieu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonPhongChieu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonPhongChieu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonPhongChieu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonPhongChieu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonPhongChieu.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonPhongChieu.ForeColor = System.Drawing.Color.DimGray;
            this.buttonPhongChieu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonPhongChieu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonPhongChieu.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonPhongChieu.IconMarginLeft = 11;
            this.buttonPhongChieu.IconPadding = 10;
            this.buttonPhongChieu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonPhongChieu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonPhongChieu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonPhongChieu.IconSize = 28;
            this.buttonPhongChieu.IdleBorderColor = System.Drawing.Color.White;
            this.buttonPhongChieu.IdleBorderRadius = 1;
            this.buttonPhongChieu.IdleBorderThickness = 1;
            this.buttonPhongChieu.IdleFillColor = System.Drawing.Color.White;
            this.buttonPhongChieu.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhongChieu_OFF;
            this.buttonPhongChieu.IdleIconRightImage = null;
            this.buttonPhongChieu.IndicateFocus = true;
            this.buttonPhongChieu.Location = new System.Drawing.Point(25, 220);
            this.buttonPhongChieu.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonPhongChieu.Name = "buttonPhongChieu";
            this.buttonPhongChieu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonPhongChieu.OnDisabledState.BorderRadius = 1;
            this.buttonPhongChieu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhongChieu.OnDisabledState.BorderThickness = 1;
            this.buttonPhongChieu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonPhongChieu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonPhongChieu.OnDisabledState.IconLeftImage = null;
            this.buttonPhongChieu.OnDisabledState.IconRightImage = null;
            this.buttonPhongChieu.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonPhongChieu.onHoverState.BorderRadius = 1;
            this.buttonPhongChieu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhongChieu.onHoverState.BorderThickness = 1;
            this.buttonPhongChieu.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonPhongChieu.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonPhongChieu.onHoverState.IconLeftImage = null;
            this.buttonPhongChieu.onHoverState.IconRightImage = null;
            this.buttonPhongChieu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonPhongChieu.OnIdleState.BorderRadius = 1;
            this.buttonPhongChieu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhongChieu.OnIdleState.BorderThickness = 1;
            this.buttonPhongChieu.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonPhongChieu.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonPhongChieu.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhongChieu_OFF;
            this.buttonPhongChieu.OnIdleState.IconRightImage = null;
            this.buttonPhongChieu.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonPhongChieu.OnPressedState.BorderRadius = 1;
            this.buttonPhongChieu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhongChieu.OnPressedState.BorderThickness = 1;
            this.buttonPhongChieu.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonPhongChieu.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonPhongChieu.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhongChieu_ON;
            this.buttonPhongChieu.OnPressedState.IconRightImage = null;
            this.buttonPhongChieu.Size = new System.Drawing.Size(298, 46);
            this.buttonPhongChieu.TabIndex = 14;
            this.buttonPhongChieu.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonPhongChieu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonPhongChieu.TextMarginLeft = 0;
            this.buttonPhongChieu.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonPhongChieu.UseDefaultRadiusAndThickness = true;
            // 
            // buttonPhim
            // 
            this.buttonPhim.AllowAnimations = true;
            this.buttonPhim.AllowMouseEffects = true;
            this.buttonPhim.AllowToggling = true;
            this.buttonPhim.AnimationSpeed = 150;
            this.buttonPhim.AutoGenerateColors = false;
            this.buttonPhim.AutoRoundBorders = false;
            this.buttonPhim.AutoSizeLeftIcon = false;
            this.buttonPhim.AutoSizeRightIcon = true;
            this.buttonPhim.BackColor = System.Drawing.Color.Transparent;
            this.buttonPhim.BackColor1 = System.Drawing.Color.White;
            this.buttonPhim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonPhim.BackgroundImage")));
            this.buttonPhim.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.ButtonText = "Quản lý phim";
            this.buttonPhim.ButtonTextMarginLeft = 0;
            this.buttonPhim.ColorContrastOnClick = 45;
            this.buttonPhim.ColorContrastOnHover = 45;
            this.buttonPhim.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.buttonPhim.CustomizableEdges = borderEdges4;
            this.buttonPhim.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonPhim.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonPhim.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonPhim.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonPhim.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonPhim.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonPhim.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonPhim.ForeColor = System.Drawing.Color.DimGray;
            this.buttonPhim.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonPhim.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonPhim.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonPhim.IconMarginLeft = 11;
            this.buttonPhim.IconPadding = 10;
            this.buttonPhim.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonPhim.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonPhim.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonPhim.IconSize = 28;
            this.buttonPhim.IdleBorderColor = System.Drawing.Color.White;
            this.buttonPhim.IdleBorderRadius = 1;
            this.buttonPhim.IdleBorderThickness = 1;
            this.buttonPhim.IdleFillColor = System.Drawing.Color.White;
            this.buttonPhim.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhim_OFF;
            this.buttonPhim.IdleIconRightImage = null;
            this.buttonPhim.IndicateFocus = true;
            this.buttonPhim.Location = new System.Drawing.Point(25, 58);
            this.buttonPhim.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonPhim.Name = "buttonPhim";
            this.buttonPhim.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonPhim.OnDisabledState.BorderRadius = 1;
            this.buttonPhim.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.OnDisabledState.BorderThickness = 1;
            this.buttonPhim.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonPhim.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonPhim.OnDisabledState.IconLeftImage = null;
            this.buttonPhim.OnDisabledState.IconRightImage = null;
            this.buttonPhim.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonPhim.onHoverState.BorderRadius = 1;
            this.buttonPhim.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.onHoverState.BorderThickness = 1;
            this.buttonPhim.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonPhim.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonPhim.onHoverState.IconLeftImage = null;
            this.buttonPhim.onHoverState.IconRightImage = null;
            this.buttonPhim.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonPhim.OnIdleState.BorderRadius = 1;
            this.buttonPhim.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.OnIdleState.BorderThickness = 1;
            this.buttonPhim.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonPhim.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonPhim.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhim_OFF;
            this.buttonPhim.OnIdleState.IconRightImage = null;
            this.buttonPhim.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonPhim.OnPressedState.BorderRadius = 1;
            this.buttonPhim.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.OnPressedState.BorderThickness = 1;
            this.buttonPhim.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonPhim.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonPhim.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhim_ON;
            this.buttonPhim.OnPressedState.IconRightImage = null;
            this.buttonPhim.Size = new System.Drawing.Size(298, 46);
            this.buttonPhim.TabIndex = 11;
            this.buttonPhim.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonPhim.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonPhim.TextMarginLeft = 0;
            this.buttonPhim.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonPhim.UseDefaultRadiusAndThickness = true;
            this.buttonPhim.Click += new System.EventHandler(this.buttonPhim_Click);
            // 
            // buttonTaiKhoan
            // 
            this.buttonTaiKhoan.AllowAnimations = true;
            this.buttonTaiKhoan.AllowMouseEffects = true;
            this.buttonTaiKhoan.AllowToggling = true;
            this.buttonTaiKhoan.AnimationSpeed = 150;
            this.buttonTaiKhoan.AutoGenerateColors = false;
            this.buttonTaiKhoan.AutoRoundBorders = false;
            this.buttonTaiKhoan.AutoSizeLeftIcon = false;
            this.buttonTaiKhoan.AutoSizeRightIcon = true;
            this.buttonTaiKhoan.BackColor = System.Drawing.Color.Transparent;
            this.buttonTaiKhoan.BackColor1 = System.Drawing.Color.White;
            this.buttonTaiKhoan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonTaiKhoan.BackgroundImage")));
            this.buttonTaiKhoan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTaiKhoan.ButtonText = "Quản lý tài khoản";
            this.buttonTaiKhoan.ButtonTextMarginLeft = 0;
            this.buttonTaiKhoan.ColorContrastOnClick = 45;
            this.buttonTaiKhoan.ColorContrastOnHover = 45;
            this.buttonTaiKhoan.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.buttonTaiKhoan.CustomizableEdges = borderEdges5;
            this.buttonTaiKhoan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonTaiKhoan.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonTaiKhoan.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonTaiKhoan.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTaiKhoan.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonTaiKhoan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonTaiKhoan.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonTaiKhoan.ForeColor = System.Drawing.Color.DimGray;
            this.buttonTaiKhoan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonTaiKhoan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonTaiKhoan.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonTaiKhoan.IconMarginLeft = 11;
            this.buttonTaiKhoan.IconPadding = 10;
            this.buttonTaiKhoan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonTaiKhoan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonTaiKhoan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonTaiKhoan.IconSize = 28;
            this.buttonTaiKhoan.IdleBorderColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.IdleBorderRadius = 1;
            this.buttonTaiKhoan.IdleBorderThickness = 1;
            this.buttonTaiKhoan.IdleFillColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyTaiKhoan_OFF;
            this.buttonTaiKhoan.IdleIconRightImage = null;
            this.buttonTaiKhoan.IndicateFocus = true;
            this.buttonTaiKhoan.Location = new System.Drawing.Point(25, 166);
            this.buttonTaiKhoan.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonTaiKhoan.Name = "buttonTaiKhoan";
            this.buttonTaiKhoan.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonTaiKhoan.OnDisabledState.BorderRadius = 1;
            this.buttonTaiKhoan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTaiKhoan.OnDisabledState.BorderThickness = 1;
            this.buttonTaiKhoan.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonTaiKhoan.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTaiKhoan.OnDisabledState.IconLeftImage = null;
            this.buttonTaiKhoan.OnDisabledState.IconRightImage = null;
            this.buttonTaiKhoan.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.onHoverState.BorderRadius = 1;
            this.buttonTaiKhoan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTaiKhoan.onHoverState.BorderThickness = 1;
            this.buttonTaiKhoan.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonTaiKhoan.onHoverState.IconLeftImage = null;
            this.buttonTaiKhoan.onHoverState.IconRightImage = null;
            this.buttonTaiKhoan.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.OnIdleState.BorderRadius = 1;
            this.buttonTaiKhoan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTaiKhoan.OnIdleState.BorderThickness = 1;
            this.buttonTaiKhoan.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonTaiKhoan.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyTaiKhoan_OFF;
            this.buttonTaiKhoan.OnIdleState.IconRightImage = null;
            this.buttonTaiKhoan.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.OnPressedState.BorderRadius = 1;
            this.buttonTaiKhoan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTaiKhoan.OnPressedState.BorderThickness = 1;
            this.buttonTaiKhoan.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonTaiKhoan.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonTaiKhoan.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyTaiKhoan_ON;
            this.buttonTaiKhoan.OnPressedState.IconRightImage = null;
            this.buttonTaiKhoan.Size = new System.Drawing.Size(298, 46);
            this.buttonTaiKhoan.TabIndex = 13;
            this.buttonTaiKhoan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonTaiKhoan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonTaiKhoan.TextMarginLeft = 0;
            this.buttonTaiKhoan.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonTaiKhoan.UseDefaultRadiusAndThickness = true;
            this.buttonTaiKhoan.Click += new System.EventHandler(this.buttonTaiKhoan_Click);
            // 
            // buttonSuatChieu
            // 
            this.buttonSuatChieu.AllowAnimations = true;
            this.buttonSuatChieu.AllowMouseEffects = true;
            this.buttonSuatChieu.AllowToggling = true;
            this.buttonSuatChieu.AnimationSpeed = 150;
            this.buttonSuatChieu.AutoGenerateColors = false;
            this.buttonSuatChieu.AutoRoundBorders = false;
            this.buttonSuatChieu.AutoSizeLeftIcon = false;
            this.buttonSuatChieu.AutoSizeRightIcon = true;
            this.buttonSuatChieu.BackColor = System.Drawing.Color.Transparent;
            this.buttonSuatChieu.BackColor1 = System.Drawing.Color.White;
            this.buttonSuatChieu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonSuatChieu.BackgroundImage")));
            this.buttonSuatChieu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonSuatChieu.ButtonText = "Quản lý suất chiếu";
            this.buttonSuatChieu.ButtonTextMarginLeft = 0;
            this.buttonSuatChieu.ColorContrastOnClick = 45;
            this.buttonSuatChieu.ColorContrastOnHover = 45;
            this.buttonSuatChieu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.buttonSuatChieu.CustomizableEdges = borderEdges6;
            this.buttonSuatChieu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonSuatChieu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonSuatChieu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonSuatChieu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonSuatChieu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonSuatChieu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonSuatChieu.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonSuatChieu.ForeColor = System.Drawing.Color.DimGray;
            this.buttonSuatChieu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonSuatChieu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonSuatChieu.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonSuatChieu.IconMarginLeft = 11;
            this.buttonSuatChieu.IconPadding = 10;
            this.buttonSuatChieu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonSuatChieu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonSuatChieu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonSuatChieu.IconSize = 28;
            this.buttonSuatChieu.IdleBorderColor = System.Drawing.Color.White;
            this.buttonSuatChieu.IdleBorderRadius = 1;
            this.buttonSuatChieu.IdleBorderThickness = 1;
            this.buttonSuatChieu.IdleFillColor = System.Drawing.Color.White;
            this.buttonSuatChieu.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLySuatChieu_OFF;
            this.buttonSuatChieu.IdleIconRightImage = null;
            this.buttonSuatChieu.IndicateFocus = true;
            this.buttonSuatChieu.Location = new System.Drawing.Point(25, 112);
            this.buttonSuatChieu.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonSuatChieu.Name = "buttonSuatChieu";
            this.buttonSuatChieu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonSuatChieu.OnDisabledState.BorderRadius = 1;
            this.buttonSuatChieu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonSuatChieu.OnDisabledState.BorderThickness = 1;
            this.buttonSuatChieu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonSuatChieu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonSuatChieu.OnDisabledState.IconLeftImage = null;
            this.buttonSuatChieu.OnDisabledState.IconRightImage = null;
            this.buttonSuatChieu.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonSuatChieu.onHoverState.BorderRadius = 1;
            this.buttonSuatChieu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonSuatChieu.onHoverState.BorderThickness = 1;
            this.buttonSuatChieu.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonSuatChieu.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonSuatChieu.onHoverState.IconLeftImage = null;
            this.buttonSuatChieu.onHoverState.IconRightImage = null;
            this.buttonSuatChieu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonSuatChieu.OnIdleState.BorderRadius = 1;
            this.buttonSuatChieu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonSuatChieu.OnIdleState.BorderThickness = 1;
            this.buttonSuatChieu.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonSuatChieu.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonSuatChieu.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLySuatChieu_OFF;
            this.buttonSuatChieu.OnIdleState.IconRightImage = null;
            this.buttonSuatChieu.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonSuatChieu.OnPressedState.BorderRadius = 1;
            this.buttonSuatChieu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonSuatChieu.OnPressedState.BorderThickness = 1;
            this.buttonSuatChieu.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonSuatChieu.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonSuatChieu.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLySuatChieu_ON;
            this.buttonSuatChieu.OnPressedState.IconRightImage = null;
            this.buttonSuatChieu.Size = new System.Drawing.Size(298, 46);
            this.buttonSuatChieu.TabIndex = 12;
            this.buttonSuatChieu.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonSuatChieu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonSuatChieu.TextMarginLeft = 0;
            this.buttonSuatChieu.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonSuatChieu.UseDefaultRadiusAndThickness = true;
            this.buttonSuatChieu.Click += new System.EventHandler(this.buttonSuatChieu_Click);
            // 
            // buttonTrangChu
            // 
            this.buttonTrangChu.AllowAnimations = true;
            this.buttonTrangChu.AllowMouseEffects = true;
            this.buttonTrangChu.AllowToggling = true;
            this.buttonTrangChu.AnimationSpeed = 150;
            this.buttonTrangChu.AutoGenerateColors = false;
            this.buttonTrangChu.AutoRoundBorders = false;
            this.buttonTrangChu.AutoSizeLeftIcon = false;
            this.buttonTrangChu.AutoSizeRightIcon = true;
            this.buttonTrangChu.BackColor = System.Drawing.Color.Transparent;
            this.buttonTrangChu.BackColor1 = System.Drawing.Color.White;
            this.buttonTrangChu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonTrangChu.BackgroundImage")));
            this.buttonTrangChu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.ButtonText = "Doanh Thu";
            this.buttonTrangChu.ButtonTextMarginLeft = 0;
            this.buttonTrangChu.ColorContrastOnClick = 45;
            this.buttonTrangChu.ColorContrastOnHover = 45;
            this.buttonTrangChu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.buttonTrangChu.CustomizableEdges = borderEdges7;
            this.buttonTrangChu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonTrangChu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonTrangChu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonTrangChu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTrangChu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonTrangChu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonTrangChu.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonTrangChu.ForeColor = System.Drawing.Color.DimGray;
            this.buttonTrangChu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonTrangChu.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.buttonTrangChu.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonTrangChu.IconMarginLeft = 11;
            this.buttonTrangChu.IconPadding = 10;
            this.buttonTrangChu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonTrangChu.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.buttonTrangChu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonTrangChu.IconSize = 28;
            this.buttonTrangChu.IdleBorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.IdleBorderRadius = 1;
            this.buttonTrangChu.IdleBorderThickness = 1;
            this.buttonTrangChu.IdleFillColor = System.Drawing.Color.White;
            this.buttonTrangChu.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.DoanhThu_OFF;
            this.buttonTrangChu.IdleIconRightImage = null;
            this.buttonTrangChu.IndicateFocus = true;
            this.buttonTrangChu.Location = new System.Drawing.Point(25, 4);
            this.buttonTrangChu.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonTrangChu.Name = "buttonTrangChu";
            this.buttonTrangChu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonTrangChu.OnDisabledState.BorderRadius = 1;
            this.buttonTrangChu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.OnDisabledState.BorderThickness = 1;
            this.buttonTrangChu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonTrangChu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTrangChu.OnDisabledState.IconLeftImage = null;
            this.buttonTrangChu.OnDisabledState.IconRightImage = null;
            this.buttonTrangChu.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.onHoverState.BorderRadius = 1;
            this.buttonTrangChu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.onHoverState.BorderThickness = 1;
            this.buttonTrangChu.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonTrangChu.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonTrangChu.onHoverState.IconLeftImage = null;
            this.buttonTrangChu.onHoverState.IconRightImage = null;
            this.buttonTrangChu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnIdleState.BorderRadius = 1;
            this.buttonTrangChu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.OnIdleState.BorderThickness = 1;
            this.buttonTrangChu.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonTrangChu.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.DoanhThu_OFF;
            this.buttonTrangChu.OnIdleState.IconRightImage = null;
            this.buttonTrangChu.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnPressedState.BorderRadius = 1;
            this.buttonTrangChu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.OnPressedState.BorderThickness = 1;
            this.buttonTrangChu.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonTrangChu.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.DoanhThu_ON;
            this.buttonTrangChu.OnPressedState.IconRightImage = null;
            this.buttonTrangChu.Size = new System.Drawing.Size(298, 46);
            this.buttonTrangChu.TabIndex = 10;
            this.buttonTrangChu.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonTrangChu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonTrangChu.TextMarginLeft = 0;
            this.buttonTrangChu.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonTrangChu.UseDefaultRadiusAndThickness = true;
            this.buttonTrangChu.Click += new System.EventHandler(this.buttonTrangChu_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(42)))), ((int)(((byte)(42)))));
            this.bunifuPanel2.BorderRadius = 0;
            this.bunifuPanel2.BorderThickness = 0;
            this.bunifuPanel2.Controls.Add(this.tableLayoutPanel2);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel2.Location = new System.Drawing.Point(327, 0);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.Padding = new System.Windows.Forms.Padding(43, 20, 43, 20);
            this.bunifuPanel2.ShowBorders = false;
            this.bunifuPanel2.Size = new System.Drawing.Size(1486, 106);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 72F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel3, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.bunifuPictureBox1, 0, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(1110, 20);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(333, 66);
            this.tableLayoutPanel2.TabIndex = 3;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Controls.Add(this.labelQuyen, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.labelTenDangNhap, 0, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(76, 4);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 2;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(253, 58);
            this.tableLayoutPanel3.TabIndex = 3;
            // 
            // labelQuyen
            // 
            this.labelQuyen.AutoSize = true;
            this.labelQuyen.BackColor = System.Drawing.Color.Transparent;
            this.labelQuyen.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelQuyen.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(126)))), ((int)(((byte)(126)))), ((int)(((byte)(126)))));
            this.labelQuyen.Location = new System.Drawing.Point(4, 29);
            this.labelQuyen.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelQuyen.Name = "labelQuyen";
            this.labelQuyen.Size = new System.Drawing.Size(109, 23);
            this.labelQuyen.TabIndex = 4;
            this.labelQuyen.Text = "Super Admin";
            // 
            // labelTenDangNhap
            // 
            this.labelTenDangNhap.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.labelTenDangNhap.AutoSize = true;
            this.labelTenDangNhap.BackColor = System.Drawing.Color.Transparent;
            this.labelTenDangNhap.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelTenDangNhap.Location = new System.Drawing.Point(4, 0);
            this.labelTenDangNhap.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelTenDangNhap.Name = "labelTenDangNhap";
            this.labelTenDangNhap.Size = new System.Drawing.Size(133, 29);
            this.labelTenDangNhap.TabIndex = 3;
            this.labelTenDangNhap.Text = "@Username";
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 32;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(4, 4);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(64, 64);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // DashboardForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.ClientSize = new System.Drawing.Size(1813, 945);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.IsMdiContainer = true;
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "DashboardForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Bảng điều khiển";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.DashboardForm_FormClosed);
            this.Load += new System.EventHandler(this.DashboardForm_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonTrangChu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonSuatChieu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonPhim;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonBaoCao;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonPhongChieu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonTaiKhoan;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Label labelQuyen;
        private System.Windows.Forms.Label labelTenDangNhap;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonDatVe;
    }
}