namespace QuanLyRapChieuPhim.MainForm
{
    partial class DashboardForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DashboardForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuButton23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonPhim = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonNhanVien = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.buttonTrangChu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.labelQuyen = new System.Windows.Forms.Label();
            this.labelTenDangNhap = new System.Windows.Forms.Label();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.textboxTenNV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textboxSDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buttonInsert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridViewKhachHang = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.MaKhachHang = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TenKhachHang = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.SDT = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.NgayTao = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Sua = new System.Windows.Forms.DataGridViewButtonColumn();
            this.Xoa = new System.Windows.Forms.DataGridViewButtonColumn();
            this.bunifuPanel1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewKhachHang)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(42)))), ((int)(((byte)(42)))));
            this.bunifuPanel1.BorderRadius = 0;
            this.bunifuPanel1.BorderThickness = 0;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.Padding = new System.Windows.Forms.Padding(32);
            this.bunifuPanel1.ShowBorders = false;
            this.bunifuPanel1.Size = new System.Drawing.Size(245, 768);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 30F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Red;
            this.bunifuLabel1.Location = new System.Drawing.Point(32, 32);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(104, 54);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "GALA";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.bunifuButton23, 0, 5);
            this.tableLayoutPanel1.Controls.Add(this.bunifuButton22, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.buttonPhim, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.bunifuButton21, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.buttonNhanVien, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.buttonTrangChu, 0, 0);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 138);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.Padding = new System.Windows.Forms.Padding(16, 0, 0, 0);
            this.tableLayoutPanel1.RowCount = 6;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(245, 264);
            this.tableLayoutPanel1.TabIndex = 3;
            // 
            // bunifuButton23
            // 
            this.bunifuButton23.AllowAnimations = true;
            this.bunifuButton23.AllowMouseEffects = true;
            this.bunifuButton23.AllowToggling = true;
            this.bunifuButton23.AnimationSpeed = 150;
            this.bunifuButton23.AutoGenerateColors = false;
            this.bunifuButton23.AutoRoundBorders = false;
            this.bunifuButton23.AutoSizeLeftIcon = false;
            this.bunifuButton23.AutoSizeRightIcon = true;
            this.bunifuButton23.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton23.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton23.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton23.BackgroundImage")));
            this.bunifuButton23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.ButtonText = "Báo cáo";
            this.bunifuButton23.ButtonTextMarginLeft = 0;
            this.bunifuButton23.ColorContrastOnClick = 45;
            this.bunifuButton23.ColorContrastOnHover = 45;
            this.bunifuButton23.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton23.CustomizableEdges = borderEdges1;
            this.bunifuButton23.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton23.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuButton23.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.bunifuButton23.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton23.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton23.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton23.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.bunifuButton23.IconMarginLeft = 11;
            this.bunifuButton23.IconPadding = 10;
            this.bunifuButton23.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton23.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton23.IconSize = 28;
            this.bunifuButton23.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton23.IdleBorderRadius = 1;
            this.bunifuButton23.IdleBorderThickness = 1;
            this.bunifuButton23.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton23.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_OFF;
            this.bunifuButton23.IdleIconRightImage = null;
            this.bunifuButton23.IndicateFocus = true;
            this.bunifuButton23.Location = new System.Drawing.Point(19, 223);
            this.bunifuButton23.Name = "bunifuButton23";
            this.bunifuButton23.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.OnDisabledState.BorderRadius = 1;
            this.bunifuButton23.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnDisabledState.BorderThickness = 1;
            this.bunifuButton23.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.OnDisabledState.IconLeftImage = null;
            this.bunifuButton23.OnDisabledState.IconRightImage = null;
            this.bunifuButton23.onHoverState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton23.onHoverState.BorderRadius = 1;
            this.bunifuButton23.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.onHoverState.BorderThickness = 1;
            this.bunifuButton23.onHoverState.FillColor = System.Drawing.Color.White;
            this.bunifuButton23.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton23.onHoverState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_ON;
            this.bunifuButton23.onHoverState.IconRightImage = null;
            this.bunifuButton23.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton23.OnIdleState.BorderRadius = 1;
            this.bunifuButton23.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnIdleState.BorderThickness = 1;
            this.bunifuButton23.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton23.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton23.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_OFF;
            this.bunifuButton23.OnIdleState.IconRightImage = null;
            this.bunifuButton23.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton23.OnPressedState.BorderRadius = 1;
            this.bunifuButton23.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnPressedState.BorderThickness = 1;
            this.bunifuButton23.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bunifuButton23.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton23.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.BaoCao_ON;
            this.bunifuButton23.OnPressedState.IconRightImage = null;
            this.bunifuButton23.Size = new System.Drawing.Size(223, 38);
            this.bunifuButton23.TabIndex = 15;
            this.bunifuButton23.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton23.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton23.TextMarginLeft = 0;
            this.bunifuButton23.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.bunifuButton23.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = true;
            this.bunifuButton22.AnimationSpeed = 150;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = false;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Quản lý phòng chiếu";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges2;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton22.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 28;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton22.IdleBorderRadius = 1;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton22.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhongChieu_OFF;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = true;
            this.bunifuButton22.Location = new System.Drawing.Point(19, 179);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 1;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.BorderRadius = 1;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton22.onHoverState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhongChieu_ON;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.BorderRadius = 1;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton22.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhongChieu_OFF;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.BorderRadius = 1;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton22.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhongChieu_ON;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(223, 38);
            this.bunifuButton22.TabIndex = 14;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            // 
            // buttonPhim
            // 
            this.buttonPhim.AllowAnimations = true;
            this.buttonPhim.AllowMouseEffects = true;
            this.buttonPhim.AllowToggling = true;
            this.buttonPhim.AnimationSpeed = 150;
            this.buttonPhim.AutoGenerateColors = false;
            this.buttonPhim.AutoRoundBorders = false;
            this.buttonPhim.AutoSizeLeftIcon = false;
            this.buttonPhim.AutoSizeRightIcon = true;
            this.buttonPhim.BackColor = System.Drawing.Color.Transparent;
            this.buttonPhim.BackColor1 = System.Drawing.Color.White;
            this.buttonPhim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonPhim.BackgroundImage")));
            this.buttonPhim.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.ButtonText = "Quản lý phim";
            this.buttonPhim.ButtonTextMarginLeft = 0;
            this.buttonPhim.ColorContrastOnClick = 45;
            this.buttonPhim.ColorContrastOnHover = 45;
            this.buttonPhim.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.buttonPhim.CustomizableEdges = borderEdges3;
            this.buttonPhim.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonPhim.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonPhim.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonPhim.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonPhim.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonPhim.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonPhim.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonPhim.ForeColor = System.Drawing.Color.DimGray;
            this.buttonPhim.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonPhim.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonPhim.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonPhim.IconMarginLeft = 11;
            this.buttonPhim.IconPadding = 10;
            this.buttonPhim.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonPhim.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonPhim.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonPhim.IconSize = 28;
            this.buttonPhim.IdleBorderColor = System.Drawing.Color.White;
            this.buttonPhim.IdleBorderRadius = 1;
            this.buttonPhim.IdleBorderThickness = 1;
            this.buttonPhim.IdleFillColor = System.Drawing.Color.White;
            this.buttonPhim.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhim_OFF;
            this.buttonPhim.IdleIconRightImage = null;
            this.buttonPhim.IndicateFocus = true;
            this.buttonPhim.Location = new System.Drawing.Point(19, 47);
            this.buttonPhim.Name = "buttonPhim";
            this.buttonPhim.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonPhim.OnDisabledState.BorderRadius = 1;
            this.buttonPhim.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.OnDisabledState.BorderThickness = 1;
            this.buttonPhim.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonPhim.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonPhim.OnDisabledState.IconLeftImage = null;
            this.buttonPhim.OnDisabledState.IconRightImage = null;
            this.buttonPhim.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonPhim.onHoverState.BorderRadius = 1;
            this.buttonPhim.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.onHoverState.BorderThickness = 1;
            this.buttonPhim.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonPhim.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonPhim.onHoverState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhim_ON;
            this.buttonPhim.onHoverState.IconRightImage = null;
            this.buttonPhim.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonPhim.OnIdleState.BorderRadius = 1;
            this.buttonPhim.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.OnIdleState.BorderThickness = 1;
            this.buttonPhim.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonPhim.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonPhim.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhim_OFF;
            this.buttonPhim.OnIdleState.IconRightImage = null;
            this.buttonPhim.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonPhim.OnPressedState.BorderRadius = 1;
            this.buttonPhim.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonPhim.OnPressedState.BorderThickness = 1;
            this.buttonPhim.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonPhim.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonPhim.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyPhim_ON;
            this.buttonPhim.OnPressedState.IconRightImage = null;
            this.buttonPhim.Size = new System.Drawing.Size(223, 38);
            this.buttonPhim.TabIndex = 11;
            this.buttonPhim.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonPhim.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonPhim.TextMarginLeft = 0;
            this.buttonPhim.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonPhim.UseDefaultRadiusAndThickness = true;
            this.buttonPhim.Click += new System.EventHandler(this.buttonPhim_Click);
            this.buttonPhim.MouseLeave += new System.EventHandler(this.buttonPhim_MouseLeave);
            this.buttonPhim.MouseMove += new System.Windows.Forms.MouseEventHandler(this.buttonPhim_MouseMove);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = true;
            this.bunifuButton21.AnimationSpeed = 150;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = false;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Quản lý tài khoản";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges4;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 28;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton21.IdleBorderRadius = 1;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton21.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyTaiKhoan_OFF;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = true;
            this.bunifuButton21.Location = new System.Drawing.Point(19, 135);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 1;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.BorderRadius = 1;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.onHoverState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyTaiKhoan_ON;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.BorderRadius = 1;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyTaiKhoan_OFF;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.BorderRadius = 1;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLyTaiKhoan_ON;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(223, 38);
            this.bunifuButton21.TabIndex = 13;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // buttonNhanVien
            // 
            this.buttonNhanVien.AllowAnimations = true;
            this.buttonNhanVien.AllowMouseEffects = true;
            this.buttonNhanVien.AllowToggling = true;
            this.buttonNhanVien.AnimationSpeed = 150;
            this.buttonNhanVien.AutoGenerateColors = false;
            this.buttonNhanVien.AutoRoundBorders = false;
            this.buttonNhanVien.AutoSizeLeftIcon = false;
            this.buttonNhanVien.AutoSizeRightIcon = true;
            this.buttonNhanVien.BackColor = System.Drawing.Color.Transparent;
            this.buttonNhanVien.BackColor1 = System.Drawing.Color.White;
            this.buttonNhanVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonNhanVien.BackgroundImage")));
            this.buttonNhanVien.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonNhanVien.ButtonText = "Quản lý suất chiếu";
            this.buttonNhanVien.ButtonTextMarginLeft = 0;
            this.buttonNhanVien.ColorContrastOnClick = 45;
            this.buttonNhanVien.ColorContrastOnHover = 45;
            this.buttonNhanVien.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.buttonNhanVien.CustomizableEdges = borderEdges5;
            this.buttonNhanVien.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonNhanVien.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonNhanVien.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonNhanVien.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonNhanVien.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonNhanVien.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonNhanVien.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonNhanVien.ForeColor = System.Drawing.Color.DimGray;
            this.buttonNhanVien.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonNhanVien.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonNhanVien.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonNhanVien.IconMarginLeft = 11;
            this.buttonNhanVien.IconPadding = 10;
            this.buttonNhanVien.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonNhanVien.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonNhanVien.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonNhanVien.IconSize = 28;
            this.buttonNhanVien.IdleBorderColor = System.Drawing.Color.White;
            this.buttonNhanVien.IdleBorderRadius = 1;
            this.buttonNhanVien.IdleBorderThickness = 1;
            this.buttonNhanVien.IdleFillColor = System.Drawing.Color.White;
            this.buttonNhanVien.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLySuatChieu_OFF;
            this.buttonNhanVien.IdleIconRightImage = null;
            this.buttonNhanVien.IndicateFocus = true;
            this.buttonNhanVien.Location = new System.Drawing.Point(19, 91);
            this.buttonNhanVien.Name = "buttonNhanVien";
            this.buttonNhanVien.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonNhanVien.OnDisabledState.BorderRadius = 1;
            this.buttonNhanVien.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonNhanVien.OnDisabledState.BorderThickness = 1;
            this.buttonNhanVien.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonNhanVien.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonNhanVien.OnDisabledState.IconLeftImage = null;
            this.buttonNhanVien.OnDisabledState.IconRightImage = null;
            this.buttonNhanVien.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonNhanVien.onHoverState.BorderRadius = 1;
            this.buttonNhanVien.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonNhanVien.onHoverState.BorderThickness = 1;
            this.buttonNhanVien.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonNhanVien.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonNhanVien.onHoverState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLySuatChieu_ON;
            this.buttonNhanVien.onHoverState.IconRightImage = null;
            this.buttonNhanVien.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonNhanVien.OnIdleState.BorderRadius = 1;
            this.buttonNhanVien.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonNhanVien.OnIdleState.BorderThickness = 1;
            this.buttonNhanVien.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonNhanVien.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonNhanVien.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLySuatChieu_OFF;
            this.buttonNhanVien.OnIdleState.IconRightImage = null;
            this.buttonNhanVien.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonNhanVien.OnPressedState.BorderRadius = 1;
            this.buttonNhanVien.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonNhanVien.OnPressedState.BorderThickness = 1;
            this.buttonNhanVien.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonNhanVien.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonNhanVien.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.QuanLySuatChieu_ON;
            this.buttonNhanVien.OnPressedState.IconRightImage = null;
            this.buttonNhanVien.Size = new System.Drawing.Size(223, 38);
            this.buttonNhanVien.TabIndex = 12;
            this.buttonNhanVien.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonNhanVien.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonNhanVien.TextMarginLeft = 0;
            this.buttonNhanVien.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonNhanVien.UseDefaultRadiusAndThickness = true;
            this.buttonNhanVien.Click += new System.EventHandler(this.buttonNhanVien_Click);
            this.buttonNhanVien.MouseLeave += new System.EventHandler(this.buttonNhanVien_MouseLeave);
            this.buttonNhanVien.MouseMove += new System.Windows.Forms.MouseEventHandler(this.buttonNhanVien_MouseMove);
            // 
            // buttonTrangChu
            // 
            this.buttonTrangChu.AllowAnimations = true;
            this.buttonTrangChu.AllowMouseEffects = true;
            this.buttonTrangChu.AllowToggling = true;
            this.buttonTrangChu.AnimationSpeed = 150;
            this.buttonTrangChu.AutoGenerateColors = false;
            this.buttonTrangChu.AutoRoundBorders = false;
            this.buttonTrangChu.AutoSizeLeftIcon = false;
            this.buttonTrangChu.AutoSizeRightIcon = true;
            this.buttonTrangChu.BackColor = System.Drawing.Color.Transparent;
            this.buttonTrangChu.BackColor1 = System.Drawing.Color.White;
            this.buttonTrangChu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonTrangChu.BackgroundImage")));
            this.buttonTrangChu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.ButtonText = "Doanh Thu";
            this.buttonTrangChu.ButtonTextMarginLeft = 0;
            this.buttonTrangChu.ColorContrastOnClick = 45;
            this.buttonTrangChu.ColorContrastOnHover = 45;
            this.buttonTrangChu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.buttonTrangChu.CustomizableEdges = borderEdges6;
            this.buttonTrangChu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonTrangChu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonTrangChu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonTrangChu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTrangChu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonTrangChu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.buttonTrangChu.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonTrangChu.ForeColor = System.Drawing.Color.DimGray;
            this.buttonTrangChu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonTrangChu.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.buttonTrangChu.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.buttonTrangChu.IconMarginLeft = 11;
            this.buttonTrangChu.IconPadding = 10;
            this.buttonTrangChu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonTrangChu.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.buttonTrangChu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonTrangChu.IconSize = 28;
            this.buttonTrangChu.IdleBorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.IdleBorderRadius = 1;
            this.buttonTrangChu.IdleBorderThickness = 1;
            this.buttonTrangChu.IdleFillColor = System.Drawing.Color.White;
            this.buttonTrangChu.IdleIconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.DoanhThu_OFF;
            this.buttonTrangChu.IdleIconRightImage = null;
            this.buttonTrangChu.IndicateFocus = true;
            this.buttonTrangChu.Location = new System.Drawing.Point(19, 3);
            this.buttonTrangChu.Name = "buttonTrangChu";
            this.buttonTrangChu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonTrangChu.OnDisabledState.BorderRadius = 1;
            this.buttonTrangChu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.OnDisabledState.BorderThickness = 1;
            this.buttonTrangChu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonTrangChu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTrangChu.OnDisabledState.IconLeftImage = null;
            this.buttonTrangChu.OnDisabledState.IconRightImage = null;
            this.buttonTrangChu.onHoverState.BorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.onHoverState.BorderRadius = 1;
            this.buttonTrangChu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.onHoverState.BorderThickness = 1;
            this.buttonTrangChu.onHoverState.FillColor = System.Drawing.Color.White;
            this.buttonTrangChu.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonTrangChu.onHoverState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.DoanhThu_ON;
            this.buttonTrangChu.onHoverState.IconRightImage = null;
            this.buttonTrangChu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnIdleState.BorderRadius = 1;
            this.buttonTrangChu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.OnIdleState.BorderThickness = 1;
            this.buttonTrangChu.OnIdleState.FillColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonTrangChu.OnIdleState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.DoanhThu_OFF;
            this.buttonTrangChu.OnIdleState.IconRightImage = null;
            this.buttonTrangChu.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnPressedState.BorderRadius = 1;
            this.buttonTrangChu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonTrangChu.OnPressedState.BorderThickness = 1;
            this.buttonTrangChu.OnPressedState.FillColor = System.Drawing.Color.White;
            this.buttonTrangChu.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonTrangChu.OnPressedState.IconLeftImage = global::QuanLyRapChieuPhim.Properties.Resources.DoanhThu_ON;
            this.buttonTrangChu.OnPressedState.IconRightImage = null;
            this.buttonTrangChu.Size = new System.Drawing.Size(223, 38);
            this.buttonTrangChu.TabIndex = 10;
            this.buttonTrangChu.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonTrangChu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonTrangChu.TextMarginLeft = 0;
            this.buttonTrangChu.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.buttonTrangChu.UseDefaultRadiusAndThickness = true;
            this.buttonTrangChu.Click += new System.EventHandler(this.buttonTrangChu_Click);
            this.buttonTrangChu.MouseLeave += new System.EventHandler(this.buttonTrangChu_MouseLeave);
            this.buttonTrangChu.MouseMove += new System.Windows.Forms.MouseEventHandler(this.buttonTrangChu_MouseMove);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(42)))), ((int)(((byte)(42)))));
            this.bunifuPanel2.BorderRadius = 0;
            this.bunifuPanel2.BorderThickness = 0;
            this.bunifuPanel2.Controls.Add(this.tableLayoutPanel2);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel2.Location = new System.Drawing.Point(245, 0);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.Padding = new System.Windows.Forms.Padding(32, 16, 32, 16);
            this.bunifuPanel2.ShowBorders = false;
            this.bunifuPanel2.Size = new System.Drawing.Size(1115, 86);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 54F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel3, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.bunifuPictureBox1, 0, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(833, 16);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(250, 54);
            this.tableLayoutPanel2.TabIndex = 3;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Controls.Add(this.labelQuyen, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.labelTenDangNhap, 0, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(57, 3);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 2;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(190, 48);
            this.tableLayoutPanel3.TabIndex = 3;
            // 
            // labelQuyen
            // 
            this.labelQuyen.AutoSize = true;
            this.labelQuyen.BackColor = System.Drawing.Color.Transparent;
            this.labelQuyen.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelQuyen.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(126)))), ((int)(((byte)(126)))), ((int)(((byte)(126)))));
            this.labelQuyen.Location = new System.Drawing.Point(3, 24);
            this.labelQuyen.Name = "labelQuyen";
            this.labelQuyen.Size = new System.Drawing.Size(90, 19);
            this.labelQuyen.TabIndex = 4;
            this.labelQuyen.Text = "Super Admin";
            // 
            // labelTenDangNhap
            // 
            this.labelTenDangNhap.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.labelTenDangNhap.AutoSize = true;
            this.labelTenDangNhap.BackColor = System.Drawing.Color.Transparent;
            this.labelTenDangNhap.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelTenDangNhap.Location = new System.Drawing.Point(3, 0);
            this.labelTenDangNhap.Name = "labelTenDangNhap";
            this.labelTenDangNhap.Size = new System.Drawing.Size(113, 24);
            this.labelTenDangNhap.TabIndex = 3;
            this.labelTenDangNhap.Text = "@Username";
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 24;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(3, 3);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(48, 48);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // textboxTenNV
            // 
            this.textboxTenNV.AcceptsReturn = false;
            this.textboxTenNV.AcceptsTab = false;
            this.textboxTenNV.AnimationSpeed = 200;
            this.textboxTenNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxTenNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxTenNV.AutoSizeHeight = true;
            this.textboxTenNV.BackColor = System.Drawing.Color.Transparent;
            this.textboxTenNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxTenNV.BackgroundImage")));
            this.textboxTenNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textboxTenNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxTenNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textboxTenNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.textboxTenNV.BorderRadius = 1;
            this.textboxTenNV.BorderThickness = 1;
            this.textboxTenNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxTenNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxTenNV.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textboxTenNV.DefaultText = "";
            this.textboxTenNV.FillColor = System.Drawing.Color.White;
            this.textboxTenNV.HideSelection = true;
            this.textboxTenNV.IconLeft = null;
            this.textboxTenNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxTenNV.IconPadding = 10;
            this.textboxTenNV.IconRight = null;
            this.textboxTenNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxTenNV.Lines = new string[0];
            this.textboxTenNV.Location = new System.Drawing.Point(385, 185);
            this.textboxTenNV.MaxLength = 32767;
            this.textboxTenNV.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxTenNV.Modified = false;
            this.textboxTenNV.Multiline = false;
            this.textboxTenNV.Name = "textboxTenNV";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxTenNV.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxTenNV.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxTenNV.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxTenNV.OnIdleState = stateProperties4;
            this.textboxTenNV.Padding = new System.Windows.Forms.Padding(3);
            this.textboxTenNV.PasswordChar = '\0';
            this.textboxTenNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textboxTenNV.PlaceholderText = "Enter text";
            this.textboxTenNV.ReadOnly = false;
            this.textboxTenNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxTenNV.SelectedText = "";
            this.textboxTenNV.SelectionLength = 0;
            this.textboxTenNV.SelectionStart = 0;
            this.textboxTenNV.ShortcutsEnabled = true;
            this.textboxTenNV.Size = new System.Drawing.Size(260, 39);
            this.textboxTenNV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxTenNV.TabIndex = 3;
            this.textboxTenNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxTenNV.TextMarginBottom = 0;
            this.textboxTenNV.TextMarginLeft = 3;
            this.textboxTenNV.TextMarginTop = 1;
            this.textboxTenNV.TextPlaceholder = "Enter text";
            this.textboxTenNV.UseSystemPasswordChar = false;
            this.textboxTenNV.WordWrap = true;
            // 
            // textboxSDT
            // 
            this.textboxSDT.AcceptsReturn = false;
            this.textboxSDT.AcceptsTab = false;
            this.textboxSDT.AnimationSpeed = 200;
            this.textboxSDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxSDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxSDT.AutoSizeHeight = true;
            this.textboxSDT.BackColor = System.Drawing.Color.Transparent;
            this.textboxSDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxSDT.BackgroundImage")));
            this.textboxSDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textboxSDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxSDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textboxSDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.textboxSDT.BorderRadius = 1;
            this.textboxSDT.BorderThickness = 1;
            this.textboxSDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxSDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxSDT.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textboxSDT.DefaultText = "";
            this.textboxSDT.FillColor = System.Drawing.Color.White;
            this.textboxSDT.HideSelection = true;
            this.textboxSDT.IconLeft = null;
            this.textboxSDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxSDT.IconPadding = 10;
            this.textboxSDT.IconRight = null;
            this.textboxSDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxSDT.Lines = new string[0];
            this.textboxSDT.Location = new System.Drawing.Point(385, 230);
            this.textboxSDT.MaxLength = 32767;
            this.textboxSDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxSDT.Modified = false;
            this.textboxSDT.Multiline = false;
            this.textboxSDT.Name = "textboxSDT";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxSDT.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxSDT.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxSDT.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxSDT.OnIdleState = stateProperties8;
            this.textboxSDT.Padding = new System.Windows.Forms.Padding(3);
            this.textboxSDT.PasswordChar = '\0';
            this.textboxSDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textboxSDT.PlaceholderText = "Enter text";
            this.textboxSDT.ReadOnly = false;
            this.textboxSDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxSDT.SelectedText = "";
            this.textboxSDT.SelectionLength = 0;
            this.textboxSDT.SelectionStart = 0;
            this.textboxSDT.ShortcutsEnabled = true;
            this.textboxSDT.Size = new System.Drawing.Size(260, 39);
            this.textboxSDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxSDT.TabIndex = 4;
            this.textboxSDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxSDT.TextMarginBottom = 0;
            this.textboxSDT.TextMarginLeft = 3;
            this.textboxSDT.TextMarginTop = 1;
            this.textboxSDT.TextPlaceholder = "Enter text";
            this.textboxSDT.UseSystemPasswordChar = false;
            this.textboxSDT.WordWrap = true;
            // 
            // buttonInsert
            // 
            this.buttonInsert.AllowAnimations = true;
            this.buttonInsert.AllowMouseEffects = true;
            this.buttonInsert.AllowToggling = false;
            this.buttonInsert.AnimationSpeed = 200;
            this.buttonInsert.AutoGenerateColors = false;
            this.buttonInsert.AutoRoundBorders = false;
            this.buttonInsert.AutoSizeLeftIcon = true;
            this.buttonInsert.AutoSizeRightIcon = true;
            this.buttonInsert.BackColor = System.Drawing.Color.Transparent;
            this.buttonInsert.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.buttonInsert.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonInsert.BackgroundImage")));
            this.buttonInsert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.ButtonText = "Insert";
            this.buttonInsert.ButtonTextMarginLeft = 0;
            this.buttonInsert.ColorContrastOnClick = 45;
            this.buttonInsert.ColorContrastOnHover = 45;
            this.buttonInsert.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.buttonInsert.CustomizableEdges = borderEdges7;
            this.buttonInsert.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonInsert.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonInsert.DisabledFillColor = System.Drawing.Color.Empty;
            this.buttonInsert.DisabledForecolor = System.Drawing.Color.Empty;
            this.buttonInsert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonInsert.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.buttonInsert.ForeColor = System.Drawing.Color.White;
            this.buttonInsert.IconLeft = null;
            this.buttonInsert.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonInsert.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonInsert.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonInsert.IconMarginLeft = 11;
            this.buttonInsert.IconPadding = 10;
            this.buttonInsert.IconRight = null;
            this.buttonInsert.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonInsert.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonInsert.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonInsert.IconSize = 25;
            this.buttonInsert.IdleBorderColor = System.Drawing.Color.Empty;
            this.buttonInsert.IdleBorderRadius = 0;
            this.buttonInsert.IdleBorderThickness = 0;
            this.buttonInsert.IdleFillColor = System.Drawing.Color.Empty;
            this.buttonInsert.IdleIconLeftImage = null;
            this.buttonInsert.IdleIconRightImage = null;
            this.buttonInsert.IndicateFocus = false;
            this.buttonInsert.Location = new System.Drawing.Point(385, 275);
            this.buttonInsert.Name = "buttonInsert";
            this.buttonInsert.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonInsert.OnDisabledState.BorderRadius = 1;
            this.buttonInsert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.OnDisabledState.BorderThickness = 1;
            this.buttonInsert.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonInsert.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonInsert.OnDisabledState.IconLeftImage = null;
            this.buttonInsert.OnDisabledState.IconRightImage = null;
            this.buttonInsert.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.buttonInsert.onHoverState.BorderRadius = 1;
            this.buttonInsert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.onHoverState.BorderThickness = 1;
            this.buttonInsert.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.buttonInsert.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonInsert.onHoverState.IconLeftImage = null;
            this.buttonInsert.onHoverState.IconRightImage = null;
            this.buttonInsert.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.buttonInsert.OnIdleState.BorderRadius = 1;
            this.buttonInsert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.OnIdleState.BorderThickness = 1;
            this.buttonInsert.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.buttonInsert.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonInsert.OnIdleState.IconLeftImage = null;
            this.buttonInsert.OnIdleState.IconRightImage = null;
            this.buttonInsert.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonInsert.OnPressedState.BorderRadius = 1;
            this.buttonInsert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.OnPressedState.BorderThickness = 1;
            this.buttonInsert.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonInsert.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonInsert.OnPressedState.IconLeftImage = null;
            this.buttonInsert.OnPressedState.IconRightImage = null;
            this.buttonInsert.Size = new System.Drawing.Size(260, 39);
            this.buttonInsert.TabIndex = 5;
            this.buttonInsert.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonInsert.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonInsert.TextMarginLeft = 0;
            this.buttonInsert.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonInsert.UseDefaultRadiusAndThickness = true;
            this.buttonInsert.Click += new System.EventHandler(this.buttonInsert_Click);
            // 
            // dataGridViewKhachHang
            // 
            this.dataGridViewKhachHang.AllowCustomTheming = true;
            this.dataGridViewKhachHang.AllowUserToDeleteRows = false;
            this.dataGridViewKhachHang.AllowUserToOrderColumns = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataGridViewKhachHang.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridViewKhachHang.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridViewKhachHang.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridViewKhachHang.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridViewKhachHang.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Pink;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.Crimson;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridViewKhachHang.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridViewKhachHang.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridViewKhachHang.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.MaKhachHang,
            this.TenKhachHang,
            this.SDT,
            this.NgayTao,
            this.Sua,
            this.Xoa});
            this.dataGridViewKhachHang.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataGridViewKhachHang.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridViewKhachHang.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridViewKhachHang.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridViewKhachHang.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridViewKhachHang.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataGridViewKhachHang.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridViewKhachHang.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Pink;
            this.dataGridViewKhachHang.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridViewKhachHang.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridViewKhachHang.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.Crimson;
            this.dataGridViewKhachHang.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridViewKhachHang.CurrentTheme.Name = null;
            this.dataGridViewKhachHang.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridViewKhachHang.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridViewKhachHang.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridViewKhachHang.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.dataGridViewKhachHang.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridViewKhachHang.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridViewKhachHang.EnableHeadersVisualStyles = false;
            this.dataGridViewKhachHang.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridViewKhachHang.HeaderBackColor = System.Drawing.Color.Pink;
            this.dataGridViewKhachHang.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridViewKhachHang.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridViewKhachHang.Location = new System.Drawing.Point(385, 320);
            this.dataGridViewKhachHang.Name = "dataGridViewKhachHang";
            this.dataGridViewKhachHang.ReadOnly = true;
            this.dataGridViewKhachHang.RowHeadersVisible = false;
            this.dataGridViewKhachHang.RowTemplate.Height = 40;
            this.dataGridViewKhachHang.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewKhachHang.Size = new System.Drawing.Size(940, 269);
            this.dataGridViewKhachHang.TabIndex = 6;
            this.dataGridViewKhachHang.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dataGridViewKhachHang.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridViewKhachHang_CellContentClick);
            // 
            // MaKhachHang
            // 
            this.MaKhachHang.HeaderText = "Mã Khách Hàng";
            this.MaKhachHang.Name = "MaKhachHang";
            this.MaKhachHang.ReadOnly = true;
            // 
            // TenKhachHang
            // 
            this.TenKhachHang.HeaderText = "Tên Khách Hàng";
            this.TenKhachHang.Name = "TenKhachHang";
            this.TenKhachHang.ReadOnly = true;
            // 
            // SDT
            // 
            this.SDT.HeaderText = "Số điện thoại";
            this.SDT.Name = "SDT";
            this.SDT.ReadOnly = true;
            // 
            // NgayTao
            // 
            this.NgayTao.HeaderText = "Ngày tạo";
            this.NgayTao.Name = "NgayTao";
            this.NgayTao.ReadOnly = true;
            // 
            // Sua
            // 
            this.Sua.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.Sua.HeaderText = "Sửa";
            this.Sua.Name = "Sua";
            this.Sua.ReadOnly = true;
            this.Sua.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.Sua.Text = "Sửa";
            this.Sua.UseColumnTextForButtonValue = true;
            // 
            // Xoa
            // 
            this.Xoa.HeaderText = "Xoá";
            this.Xoa.Name = "Xoa";
            this.Xoa.ReadOnly = true;
            this.Xoa.Text = "Xoá";
            this.Xoa.UseColumnTextForButtonValue = true;
            // 
            // DashboardForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.ClientSize = new System.Drawing.Size(1360, 768);
            this.Controls.Add(this.dataGridViewKhachHang);
            this.Controls.Add(this.buttonInsert);
            this.Controls.Add(this.textboxSDT);
            this.Controls.Add(this.textboxTenNV);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.IsMdiContainer = true;
            this.Name = "DashboardForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Bảng điều khiển";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.DashboardForm_FormClosed);
            this.Load += new System.EventHandler(this.DashboardForm_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewKhachHang)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonTrangChu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonNhanVien;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonPhim;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton23;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Label labelQuyen;
        private System.Windows.Forms.Label labelTenDangNhap;
        private Bunifu.UI.WinForms.BunifuTextBox textboxTenNV;
        private Bunifu.UI.WinForms.BunifuTextBox textboxSDT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonInsert;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridViewKhachHang;
        private System.Windows.Forms.DataGridViewTextBoxColumn MaKhachHang;
        private System.Windows.Forms.DataGridViewTextBoxColumn TenKhachHang;
        private System.Windows.Forms.DataGridViewTextBoxColumn SDT;
        private System.Windows.Forms.DataGridViewTextBoxColumn NgayTao;
        private System.Windows.Forms.DataGridViewButtonColumn Sua;
        private System.Windows.Forms.DataGridViewButtonColumn Xoa;
    }
}